Add a new prop - onEndReachedThresholdRelative
Flipkart/recyclerlistview pull request #695
Opened 2022-03-09 15:05 UTC by ElviraBurchik

## What

Adds a new prop `onEndReachedThresholdRelative` identical to the [`onEndReachedThreshold` of FlatList](https://reactnative.dev/docs/flatlist#onendreachedthreshold).

It allows to specify how far from the end (in units of visible length of the list) the bottom edge of the list must be from the end of the content to trigger the onEndReached callback

2022-03-09 15:36 UTC, naqvitalha commented on src/core/RecyclerListView.tsx
> +                const triggerOnEndThreshold = windowBound * Default.value<number>(this.props.onEndReachedThreshold, 0);
I don't think you want to multiply windowBound here

2022-03-09 15:39 UTC, naqvitalha requested changes

2022-03-09 15:39 UTC, naqvitalha commented on src/core/RecyclerListView.tsx
> +                const triggerOnEndThresholdRelative = windowBound * Default.value<number>(this.props.onEndReachedThresholdRelative, 0);
Looks like the bound here refers to maxScrollOffset so this compute can be wrong. Our check needs to be something like threshold <= this._layout.height * relative_threshold

2022-03-09 20:59 UTC, naqvitalha commented on README.md
> +| onEndReachedThresholdRelative | No | number | Specify the percent of a view in advance for the onEndReached callback |
Rephrase this IMO. It's a little difficult to understand right now.

2022-03-09 20:59 UTC, naqvitalha commented
@ElviraBurchik you will need to look into the lint issues. CI checks are failing

2022-03-10 10:22 UTC, ElviraBurchik commented
@naqvitalha I've addressed your comments and fix lint issues, but looks like I can't re-run CI check myself.

2022-03-10 14:19 UTC, naqvitalha approved these changes

2022-03-10 14:19 UTC, merged